# Generated by Django 3.2.4 on 2021-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archresource',
            name='pid',
            field=models.CharField(blank=True, help_text='Handle-PID', max_length=250, null=True, verbose_name='Handle-PID'),
        ),
    ]
