# Generated by Django 3.2.4 on 2021-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False, help_text='Check if everything is ok', verbose_name='checked')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
